### ISSUE TITLE
using json copy on a row returns 'Wrong type argument: symbolp, 26251'

### ISSUE THREAD

**Issue by reynard93** [emarsden/pgmacs#2]
it might be because i have some created_at and updated_at ISO timestamp columns, when adding a new row for these i see a number pair and when i continue i get an error or they might be two separate bugs.

![image](https://github.com/emarsden/pgmacs/assets/32264460/784944dc-7a8d-4941-a42a-d764fa8b3403)

this is when i use 'j' to try and copy a row
Wrong type argument: symbolp, 26251

**Comment by emarsden** [comment]
Thanks, I think this is fixed on HEAD now.
