### ISSUE TITLE
Add multi selection on database rows to group delete operation, add functionality to refresh current database table

### ISSUE THREAD

**Issue by reynard93** [emarsden/pgmacs#6]
Add multi selection on database rows to group delete operation, add functionality to refresh current database table

would it be possible to get these features in? i use the package daily

**Comment by emarsden** [comment]
Thanks for your suggestions. 

I have implemented (well, really fixed) the "refresh current table" functionality: in a row-list buffer "r" will redraw without refetching and "g" will refetch then redraw. 

Multirow deletion (I assume a little like in dired) would be a nice feature. This will require some changes to the table display functionality, which doesn't currently support per-row colors. I'll keep this issue open.

**Comment by emarsden** [comment]
Multirow deletion is now implemented in v0.15. See the documentation here
  
  https://emarsden.github.io/pgmacs/row-list.html

The interaction between multirow deletion and the insertion/copy/pasting of rows is currently not very well tested, but basic "mark mark unmark mark delete" functionality hopefully works well. Feedback welcome.
